<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Concerns\RespondsWithAdminViews;
use App\Http\Controllers\Controller;
use App\Models\Author;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AdminAuthorController extends Controller
{
    use RespondsWithAdminViews;

    public function index(Request $request)
    {
        $query = Author::withCount('books');

        // Search
        if ($request->has('search') && $request->search) {
            $query->search($request->search);
        }

        // Filter by status
        if ($request->has('status') && $request->status) {
            $query->where('status', $request->status === 'active' ? 1 : 0);
        }

        // Sort
        if ($request->has('sort')) {
            switch ($request->sort) {
                case 'name_asc':
                    $query->orderBy('name', 'asc');
                    break;
                case 'name_desc':
                    $query->orderBy('name', 'desc');
                    break;
                case 'books_count_desc':
                    $query->orderBy('books_count', 'desc');
                    break;
                default:
                    $query->orderBy('created_at', 'desc');
            }
        } else {
            $query->orderBy('created_at', 'desc');
        }

        $authors = $query->paginate(20);

        // Statistics
        $stats = [
            'total' => Author::count(),
            'active' => Author::where('status', true)->count(),
            'inactive' => Author::where('status', false)->count(),
        ];

        return view('admin.authors.index', compact('authors', 'stats'));
    }

    public function create()
    {
        return view('admin.authors.create');
    }

     public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'bio' => ['nullable', 'string'],
            'email' => ['nullable', 'email', 'max:255', 'unique:authors'],
            'website' => ['nullable', 'url', 'max:255'],
            'image' => ['nullable', 'image', 'mimes:jpg,jpeg,png,webp', 'max:2048'],
            'status' => ['sometimes', 'boolean'],
        ]);

        $data = $request->all();
        $data['status'] = $request->has('status');

        // Slug will be auto-generated by the model
        // No need to set slug manually

        if ($request->hasFile('image')) {
            $data['image'] = $request->file('image')->store('authors', 'public');
        }

        Author::create($data);

        return redirect()->route('admin.authors.index')
            ->with('success', __('admin.author_created') ?? 'Author created successfully');
    }

    public function show(Author $author)
    {
        // Load relationships
        $author->load(['books.category', 'books.publisher']);

        // Get statistics
        $stats = [
            'total_books' => $author->books()->count(),
            'total_revenue' => $author->books()->sum('final_price'),
            'total_views' => $author->books()->sum('views_count'),
            'total_downloads' => $author->books()->sum('downloads_count'),
        ];

        return view('admin.authors.show', compact('author', 'stats'));
    }

    public function edit(Author $author)
    {
        return $this->viewOrJson('admin.authors.edit', ['author' => $author]);
    }

     public function update(Request $request, Author $author)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'bio' => ['nullable', 'string'],
            'email' => ['nullable', 'email', 'max:255', 'unique:authors,email,' . $author->id],
            'website' => ['nullable', 'url', 'max:255'],
            'image' => ['nullable', 'image', 'mimes:jpg,jpeg,png,webp', 'max:2048'],
            'status' => ['sometimes', 'boolean'],
        ]);

        $data = $request->all();
        $data['status'] = $request->has('status');

        // Slug will be auto-generated by the model if name changed

        if ($request->hasFile('image')) {
            if ($author->image) {
                Storage::disk('public')->delete($author->image);
            }
            $data['image'] = $request->file('image')->store('authors', 'public');
        }

        $author->update($data);

        return redirect()->route('admin.authors.index')
            ->with('success', __('admin.author_updated') ?? 'Author updated successfully');
    }

    public function destroy(Author $author)
    {
        if ($author->books()->count() > 0) {
            return redirect()->route('admin.authors.index')
                ->with('error', __('admin.cannot_delete_has_books') ?? 'Cannot delete author with books');
        }

        if ($author->image) {
            Storage::disk('public')->delete($author->image);
        }

        $author->delete();

        return redirect()->route('admin.authors.index')
            ->with('success', __('admin.author_deleted') ?? 'Author deleted successfully');
    }

    private function validated(Request $request): array
    {
        return $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'bio' => ['nullable', 'string'],
            'image' => ['nullable', 'image', 'mimes:jpg,jpeg,png,webp', 'max:2048'],
            'email' => ['nullable', 'email', 'max:255'],
            'website' => ['nullable', 'url', 'max:255'],
            'status' => ['sometimes', 'boolean'],
        ]);
    }
    /**
 * Toggle author status
 */
public function toggleStatus(Author $author)
{
    $author->status = !$author->status;
    $author->save();

    return response()->json([
        'success' => true,
        'status' => $author->status,
        'message' => $author->status ? __('admin.author_activated') : __('admin.author_deactivated'),
    ]);
}

/**
 * Bulk update status for authors
 */
public function bulkStatus(Request $request)
{
    $request->validate([
        'ids' => ['required', 'array'],
        'ids.*' => ['exists:authors,id'],
        'status' => ['required', 'boolean'],
    ]);

    Author::whereIn('id', $request->ids)->update(['status' => $request->status]);

    return response()->json([
        'success' => true,
        'message' => __('admin.bulk_status_updated') ?? 'បានធ្វើបច្ចុប្បន្នភាពស្ថានភាពដោយជោគជ័យ',
    ]);
}

/**
 * Bulk upload authors
 */
public function bulkUpload(Request $request)
{
    $request->validate([
        'file' => ['required', 'file', 'mimes:csv,xlsx'],
    ]);

    // Import logic here using Laravel Excel package

    return redirect()->route('admin.authors.index')
        ->with('success', __('admin.authors_imported') ?? 'បាននាំចូលអ្នកនិពន្ធដោយជោគជ័យ');
}

/**
     * Export authors to CSV.
     */
    public function export(Request $request)
    {
        $query = Author::withCount('books');

        if ($request->has('status')) {
            $query->where('status', $request->status === 'active' ? 1 : 0);
        }

        $authors = $query->get();

        $filename = 'authors_' . date('Y-m-d_His') . '.csv';
        $path = storage_path('app/public/exports/' . $filename);

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $file = fopen($path, 'w');

        fputcsv($file, [
            'ID', 'Name', 'Slug', 'Email', 'Website',
            'Books Count', 'Status', 'Created At', 'Updated At'
        ]);

        foreach ($authors as $author) {
            fputcsv($file, [
                $author->id,
                $author->name,
                $author->slug,
                $author->email ?? '',
                $author->website ?? '',
                $author->books_count,
                $author->status ? 'Active' : 'Inactive',
                $author->created_at->format('Y-m-d H:i:s'),
                $author->updated_at->format('Y-m-d H:i:s'),
            ]);
        }

        fclose($file);

        return response()->download($path, $filename)->deleteFileAfterSend(true);
    }
}
